name: ashok_leyland_project_3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.4
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_bounce: ^1.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  getflutter: ^1.1.3
  google_fonts: ^2.0.0
  hexcolor: ^2.0.5
  intl: ^0.17.0
  lottie: ^1.2.1
  material_floating_search_bar: ^0.3.5
  open_file: ^3.2.1
  path_provider: ^2.0.7
  permission_handler: ^8.3.0
  provider: ^6.0.1
  sizer: ^2.0.15
  syncfusion_flutter_xlsio: ^19.3.54-beta
  ext_storage: ^1.0.3
  animated_splash_screen: ^1.1.0
  open_mail_app: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
